taboola_campaign_performance:
    constraints:
        not_null:
            - id
            - date_day
            - campaign_id
            - spend
        unique:
            - id
        relationships:
            - {from: campaign_id, to: taboola_campaigns, field: id}

taboola_campaigns:
    constraints:
        not_null:
            - id
            - start_date
        unique:
            - id
