version: 2

models:
    
- name: taboola_campaign_performance
  description: Base model for taboola campaign performance
  columns:
  - name: id
    tests:
    - not_null
    - unique
  - name: date_day
    tests:
    - not_null
  - name: campaign_id
    tests:
    - not_null
  - name: spend
    tests:
    - not_null

- name: taboola_campaigns
  description: Base model for taboola campaigns 
  columns:
  - name: id
    tests:
    - not_null
    - unique
  - name: start_date
    tests:
    - not_null
